/// A simple optimizer example for boolean expressions, demonstrating the basic framework and ISLE integration.
/// This example defines a simple language of boolean expressions and a cost function that counts the number of operations.
/// The optimizer will find the cheapest equivalent expression, demonstrating how to use the framework with a custom language and cost domain.
use egg::{Id, define_language};
use intarsia::SimpleOptimizerFramework;
use intarsia::framework::{PropertyAwareLanguage, property::NoProperty};
use intarsia::{ExplorerHooks, Task};
use intarsia_macros::{isle_accessors, isle_integration_full};

// 0. ISLE integration: Generate rewrite rules from the .isle file and link them to our optimizer framework.
isle_integration_full! {
    path: "isle/rules.rs",
}
use rules::Context; // Pull in the Context trait generated by ISLE, which we will implement for our optimizer.

// 1. Define the language of boolean expressions.
// 1 (a) -> Define the syntax of our language using egg's define_language macro. This will create an enum with variants for each operator and constant in our language.
// 1 (b) -> Define the language as ISLE terms in the .isle file. See isle/rules.isle for this example.
define_language! {
    pub enum BoolLang {
        // Boolean constants
        "true" = True,
        "false" = False,

        // Logical operations
        "AND" = And([Id; 2]),
        "OR" = Or([Id; 2]),
        "NOT" = Not(Id),
    }
}

// 2. Implement the PropertyAwareLanguage trait for our language, using NoProperty since we don't have any properties.
// TODO: Make a macro to do this
impl PropertyAwareLanguage<NoProperty> for BoolLang {
    fn property_req(&self, _child_index: usize) -> NoProperty {
        NoProperty
    }
}

// 4. Define the optimizer framework for our language and cost domain.
// The SimpleOptimizerFramework is a convenient type alias for an OptimizerFramework with SimpleCost and no user data.
pub type BoolOptimizer = SimpleOptimizerFramework<BoolLang, NoProperty>;

// 5. Implement the Context trait for our optimizer to link to ISLE ruleset.
impl Context for BoolOptimizer {
    // Implement extracting and constructing raw/constant values manually for the BoolLang
    fn extractor_const(&mut self, arg0: Id) -> Option<bool> {
        let node = self.egraph.get_node(arg0);
        match node {
            BoolLang::True => Some(true),
            BoolLang::False => Some(false),
            _ => None,
        }
    }

    fn constructor_const(&mut self, arg0: bool) -> Id {
        let node = if arg0 {
            BoolLang::True
        } else {
            BoolLang::False
        };
        let (id, _) = self.egraph.add_with_flag(node);
        id
    }

    // The rest of the operators can be generated using the isle_accessors macro, which creates both extractors and constructors for each operator based on the patterns we define in the .isle file.
    isle_accessors! {
        BoolLang::And(extractor_and, constructor_and, 2);
        BoolLang::Or(extractor_or, constructor_or, 2);
        BoolLang::Not(extractor_not, constructor_not, 1);
    }
}

// 6. Implement ExplorerHooks to link to the ISLE ruleset entrypoint.
impl ExplorerHooks<BoolLang> for BoolOptimizer {
    fn explore(&mut self, id: Id) -> Vec<Id> {
        let mut new_ids = Vec::new();
        // Call ISLE-generated explore function
        rules::constructor_explore(self, id, &mut new_ids);
        new_ids
    }
}

// Now, we can use this optimizer in our tests/main. See an example execution in main.rs.
