// GENERATED BY ISLE. DO NOT EDIT!
//
// Generated automatically from the instruction-selection DSL code in:
// - examples/boolean_optimizer/isle/rules.isle

#![allow(dead_code, unreachable_code, unreachable_patterns)]
#![allow(unused_imports, unused_variables, non_snake_case, unused_mut)]
#![allow(irrefutable_let_patterns, unused_assignments, non_camel_case_types)]

use super::*;  // Pulls in all external types.
use std::marker::PhantomData;

/// Context during lowering: an implementation of this trait
/// must be provided with all external constructors and extractors.
/// A mutable borrow is passed along through all lowering logic.
pub trait Context {
    fn extractor_const(&mut self, arg0: Id) -> Option<bool>;
    fn constructor_const(&mut self, arg0: bool) -> Id;
    fn extractor_var(&mut self, arg0: Id) -> Option<String>;
    fn constructor_var(&mut self, arg0: String) -> Id;
    fn extractor_and(&mut self, arg0: Id) -> Option<(Id, Id)>;
    fn constructor_and(&mut self, arg0: Id, arg1: Id) -> Id;
    fn extractor_or(&mut self, arg0: Id) -> Option<(Id, Id)>;
    fn constructor_or(&mut self, arg0: Id, arg1: Id) -> Id;
    fn extractor_not(&mut self, arg0: Id) -> Option<Id>;
    fn constructor_not(&mut self, arg0: Id) -> Id;
}

pub trait ContextIter {
    type Context;
    type Output;
    fn next(&mut self, ctx: &mut Self::Context) -> Option<Self::Output>;
    fn size_hint(&self) -> (usize, Option<usize>) { (0, None) }
}

pub trait IntoContextIter {
    type Context;
    type Output;
    type IntoIter: ContextIter<Context = Self::Context, Output = Self::Output>;
    fn into_context_iter(self) -> Self::IntoIter;
}

pub trait Length {
    fn len(&self) -> usize;
}

impl<T> Length for std::vec::Vec<T> {
    fn len(&self) -> usize {
        std::vec::Vec::len(self)
    }
}

pub struct ContextIterWrapper<I, C> {
    iter: I,
    _ctx: std::marker::PhantomData<C>,
}
impl<I: Default, C> Default for ContextIterWrapper<I, C> {
    fn default() -> Self {
        ContextIterWrapper {
            iter: I::default(),
            _ctx: std::marker::PhantomData
        }
    }
}
impl<I, C> std::ops::Deref for ContextIterWrapper<I, C> {
    type Target = I;
    fn deref(&self) -> &I {
        &self.iter
    }
}
impl<I, C> std::ops::DerefMut for ContextIterWrapper<I, C> {
    fn deref_mut(&mut self) -> &mut I {
        &mut self.iter
    }
}
impl<I: Iterator, C: Context> From<I> for ContextIterWrapper<I, C> {
    fn from(iter: I) -> Self {
        Self { iter, _ctx: std::marker::PhantomData }
    }
}
impl<I: Iterator, C: Context> ContextIter for ContextIterWrapper<I, C> {
    type Context = C;
    type Output = I::Item;
    fn next(&mut self, _ctx: &mut Self::Context) -> Option<Self::Output> {
        self.iter.next()
    }
    fn size_hint(&self) -> (usize, Option<usize>) {
        self.iter.size_hint()
    }
}
impl<I: IntoIterator, C: Context> IntoContextIter for ContextIterWrapper<I, C> {
    type Context = C;
    type Output = I::Item;
    type IntoIter = ContextIterWrapper<I::IntoIter, C>;
    fn into_context_iter(self) -> Self::IntoIter {
        ContextIterWrapper {
            iter: self.iter.into_iter(),
            _ctx: std::marker::PhantomData
        }
    }
}
impl<T, E: Extend<T>, C> Extend<T> for ContextIterWrapper<E, C> {
    fn extend<I: IntoIterator<Item = T>>(&mut self, iter: I) {
        self.iter.extend(iter);
    }
}
impl<L: Length, C> Length for ContextIterWrapper<L, C> {
    fn len(&self) -> usize {
        self.iter.len()
    }
}
           

// Generated as internal constructor for term explore.
pub fn constructor_explore<C: Context>(
    ctx: &mut C,
    arg0: Id,
    returns: &mut (impl Extend<Id> + Length),
) -> () {
    let v1 = C::extractor_not(ctx, arg0);
    if let Some(v2) = v1 {
        let v37 = C::extractor_const(ctx, v2);
        if let Some(v38) = v37 {
            match v38 {
                false => {
                    let v35 = true;
                    let v36 = C::constructor_const(ctx, v35);
                    // Rule at examples/boolean_optimizer/isle/rules.isle line 112.
                    returns.extend(Some(v36));
                    if returns.len() >= MAX_ISLE_RETURNS { return; }
                }
                true => {
                    let v31 = false;
                    let v32 = C::constructor_const(ctx, v31);
                    // Rule at examples/boolean_optimizer/isle/rules.isle line 106.
                    returns.extend(Some(v32));
                    if returns.len() >= MAX_ISLE_RETURNS { return; }
                }
                _ => {}
            }
        }
        let v3 = C::extractor_not(ctx, v2);
        if let Some(v4) = v3 {
            // Rule at examples/boolean_optimizer/isle/rules.isle line 34.
            returns.extend(Some(v4));
            if returns.len() >= MAX_ISLE_RETURNS { return; }
        }
        let v5 = C::extractor_and(ctx, v2);
        if let Some(v6) = v5 {
            let v9 = C::constructor_not(ctx, v6.0);
            let v10 = C::constructor_not(ctx, v6.1);
            let v11 = C::constructor_or(ctx, v9, v10);
            // Rule at examples/boolean_optimizer/isle/rules.isle line 41.
            returns.extend(Some(v11));
            if returns.len() >= MAX_ISLE_RETURNS { return; }
        }
        let v12 = C::extractor_or(ctx, v2);
        if let Some(v13) = v12 {
            let v16 = C::constructor_not(ctx, v13.0);
            let v17 = C::constructor_not(ctx, v13.1);
            let v18 = C::constructor_and(ctx, v16, v17);
            // Rule at examples/boolean_optimizer/isle/rules.isle line 47.
            returns.extend(Some(v18));
            if returns.len() >= MAX_ISLE_RETURNS { return; }
        }
    }
    let v19 = C::extractor_and(ctx, arg0);
    if let Some(v20) = v19 {
        let v29 = C::extractor_const(ctx, v20.1);
        if let Some(v30) = v29 {
            match v30 {
                false => {
                    let v31 = false;
                    let v32 = C::constructor_const(ctx, v31);
                    // Rule at examples/boolean_optimizer/isle/rules.isle line 80.
                    returns.extend(Some(v32));
                    if returns.len() >= MAX_ISLE_RETURNS { return; }
                }
                true => {
                    // Rule at examples/boolean_optimizer/isle/rules.isle line 93.
                    returns.extend(Some(v20.0));
                    if returns.len() >= MAX_ISLE_RETURNS { return; }
                }
                _ => {}
            }
        }
        if v20.0 == v20.1 {
            // Rule at examples/boolean_optimizer/isle/rules.isle line 54.
            returns.extend(Some(v20.0));
            if returns.len() >= MAX_ISLE_RETURNS { return; }
        }
        let v27 = C::constructor_and(ctx, v20.1, v20.0);
        // Rule at examples/boolean_optimizer/isle/rules.isle line 67.
        returns.extend(Some(v27));
        if returns.len() >= MAX_ISLE_RETURNS { return; }
    }
    let v23 = C::extractor_or(ctx, arg0);
    if let Some(v24) = v23 {
        let v33 = C::extractor_const(ctx, v24.1);
        if let Some(v34) = v33 {
            match v34 {
                false => {
                    // Rule at examples/boolean_optimizer/isle/rules.isle line 99.
                    returns.extend(Some(v24.0));
                    if returns.len() >= MAX_ISLE_RETURNS { return; }
                }
                true => {
                    let v35 = true;
                    let v36 = C::constructor_const(ctx, v35);
                    // Rule at examples/boolean_optimizer/isle/rules.isle line 86.
                    returns.extend(Some(v36));
                    if returns.len() >= MAX_ISLE_RETURNS { return; }
                }
                _ => {}
            }
        }
        if v24.0 == v24.1 {
            // Rule at examples/boolean_optimizer/isle/rules.isle line 60.
            returns.extend(Some(v24.0));
            if returns.len() >= MAX_ISLE_RETURNS { return; }
        }
        let v28 = C::constructor_or(ctx, v24.1, v24.0);
        // Rule at examples/boolean_optimizer/isle/rules.isle line 73.
        returns.extend(Some(v28));
        if returns.len() >= MAX_ISLE_RETURNS { return; }
    }
}
