// GENERATED BY ISLE. DO NOT EDIT!
//
// Generated automatically from the instruction-selection DSL code in:
// - examples/database_optimizer/isle/rules.isle

#![allow(dead_code, unreachable_code, unreachable_patterns)]
#![allow(unused_imports, unused_variables, non_snake_case, unused_mut)]
#![allow(irrefutable_let_patterns, unused_assignments, non_camel_case_types)]

use super::*;  // Pulls in all external types.
use std::marker::PhantomData;

/// Context during lowering: an implementation of this trait
/// must be provided with all external constructors and extractors.
/// A mutable borrow is passed along through all lowering logic.
pub trait Context {
    type extractor_const_val_returns: Default + IntoContextIter<Context = Self, Output = value>;
    fn extractor_const_val(&mut self, arg0: Id, returns: &mut Self::extractor_const_val_returns) -> ();
    type constructor_const_val_returns: Default + IntoContextIter<Context = Self, Output = Id>;
    fn constructor_const_val(&mut self, arg0: &value, returns: &mut Self::constructor_const_val_returns) -> ();
    fn extractor_access_table(&mut self, arg0: Id) -> Option<usize>;
    fn constructor_access_table(&mut self, arg0: usize) -> Option<Id>;
    fn extractor_access_index(&mut self, arg0: Id) -> Option<usize>;
    fn constructor_access_index(&mut self, arg0: usize) -> Option<Id>;
    fn extractor_ref_colset(&mut self, arg0: Id) -> Option<usize>;
    fn constructor_ref_colset(&mut self, arg0: usize) -> Option<Id>;
    fn extractor_combine_columns(&mut self, arg0: usize) -> Option<(usize, usize)>;
    fn constructor_combine_columns(&mut self, arg0: usize, arg1: usize) -> Option<usize>;
    type extractor_add_returns: Default + IntoContextIter<Context = Self, Output = (Id, Id)>;
    fn extractor_add(&mut self, arg0: Id, returns: &mut Self::extractor_add_returns) -> ();
    type constructor_add_returns: Default + IntoContextIter<Context = Self, Output = Id>;
    fn constructor_add(&mut self, arg0: Id, arg1: Id, returns: &mut Self::constructor_add_returns) -> ();
    type extractor_sub_returns: Default + IntoContextIter<Context = Self, Output = (Id, Id)>;
    fn extractor_sub(&mut self, arg0: Id, returns: &mut Self::extractor_sub_returns) -> ();
    type constructor_sub_returns: Default + IntoContextIter<Context = Self, Output = Id>;
    fn constructor_sub(&mut self, arg0: Id, arg1: Id, returns: &mut Self::constructor_sub_returns) -> ();
    type extractor_mul_returns: Default + IntoContextIter<Context = Self, Output = (Id, Id)>;
    fn extractor_mul(&mut self, arg0: Id, returns: &mut Self::extractor_mul_returns) -> ();
    type constructor_mul_returns: Default + IntoContextIter<Context = Self, Output = Id>;
    fn constructor_mul(&mut self, arg0: Id, arg1: Id, returns: &mut Self::constructor_mul_returns) -> ();
    type extractor_div_returns: Default + IntoContextIter<Context = Self, Output = (Id, Id)>;
    fn extractor_div(&mut self, arg0: Id, returns: &mut Self::extractor_div_returns) -> ();
    type constructor_div_returns: Default + IntoContextIter<Context = Self, Output = Id>;
    fn constructor_div(&mut self, arg0: Id, arg1: Id, returns: &mut Self::constructor_div_returns) -> ();
    type extractor_eq_returns: Default + IntoContextIter<Context = Self, Output = (Id, Id)>;
    fn extractor_eq(&mut self, arg0: Id, returns: &mut Self::extractor_eq_returns) -> ();
    type constructor_eq_returns: Default + IntoContextIter<Context = Self, Output = Id>;
    fn constructor_eq(&mut self, arg0: Id, arg1: Id, returns: &mut Self::constructor_eq_returns) -> ();
    type extractor_lt_returns: Default + IntoContextIter<Context = Self, Output = (Id, Id)>;
    fn extractor_lt(&mut self, arg0: Id, returns: &mut Self::extractor_lt_returns) -> ();
    type constructor_lt_returns: Default + IntoContextIter<Context = Self, Output = Id>;
    fn constructor_lt(&mut self, arg0: Id, arg1: Id, returns: &mut Self::constructor_lt_returns) -> ();
    type extractor_gt_returns: Default + IntoContextIter<Context = Self, Output = (Id, Id)>;
    fn extractor_gt(&mut self, arg0: Id, returns: &mut Self::extractor_gt_returns) -> ();
    type constructor_gt_returns: Default + IntoContextIter<Context = Self, Output = Id>;
    fn constructor_gt(&mut self, arg0: Id, arg1: Id, returns: &mut Self::constructor_gt_returns) -> ();
    type extractor_le_returns: Default + IntoContextIter<Context = Self, Output = (Id, Id)>;
    fn extractor_le(&mut self, arg0: Id, returns: &mut Self::extractor_le_returns) -> ();
    type constructor_le_returns: Default + IntoContextIter<Context = Self, Output = Id>;
    fn constructor_le(&mut self, arg0: Id, arg1: Id, returns: &mut Self::constructor_le_returns) -> ();
    type extractor_ge_returns: Default + IntoContextIter<Context = Self, Output = (Id, Id)>;
    fn extractor_ge(&mut self, arg0: Id, returns: &mut Self::extractor_ge_returns) -> ();
    type constructor_ge_returns: Default + IntoContextIter<Context = Self, Output = Id>;
    fn constructor_ge(&mut self, arg0: Id, arg1: Id, returns: &mut Self::constructor_ge_returns) -> ();
    type extractor_ne_returns: Default + IntoContextIter<Context = Self, Output = (Id, Id)>;
    fn extractor_ne(&mut self, arg0: Id, returns: &mut Self::extractor_ne_returns) -> ();
    type constructor_ne_returns: Default + IntoContextIter<Context = Self, Output = Id>;
    fn constructor_ne(&mut self, arg0: Id, arg1: Id, returns: &mut Self::constructor_ne_returns) -> ();
    type extractor_and_returns: Default + IntoContextIter<Context = Self, Output = (Id, Id)>;
    fn extractor_and(&mut self, arg0: Id, returns: &mut Self::extractor_and_returns) -> ();
    type constructor_and_returns: Default + IntoContextIter<Context = Self, Output = Id>;
    fn constructor_and(&mut self, arg0: Id, arg1: Id, returns: &mut Self::constructor_and_returns) -> ();
    type extractor_or_returns: Default + IntoContextIter<Context = Self, Output = (Id, Id)>;
    fn extractor_or(&mut self, arg0: Id, returns: &mut Self::extractor_or_returns) -> ();
    type constructor_or_returns: Default + IntoContextIter<Context = Self, Output = Id>;
    fn constructor_or(&mut self, arg0: Id, arg1: Id, returns: &mut Self::constructor_or_returns) -> ();
    type extractor_not_returns: Default + IntoContextIter<Context = Self, Output = Id>;
    fn extractor_not(&mut self, arg0: Id, returns: &mut Self::extractor_not_returns) -> ();
    type constructor_not_returns: Default + IntoContextIter<Context = Self, Output = Id>;
    fn constructor_not(&mut self, arg0: Id, returns: &mut Self::constructor_not_returns) -> ();
    type extractor_select_returns: Default + IntoContextIter<Context = Self, Output = (Id, Id)>;
    fn extractor_select(&mut self, arg0: Id, returns: &mut Self::extractor_select_returns) -> ();
    type constructor_select_returns: Default + IntoContextIter<Context = Self, Output = Id>;
    fn constructor_select(&mut self, arg0: Id, arg1: Id, returns: &mut Self::constructor_select_returns) -> ();
    type extractor_project_returns: Default + IntoContextIter<Context = Self, Output = (Id, Id)>;
    fn extractor_project(&mut self, arg0: Id, returns: &mut Self::extractor_project_returns) -> ();
    type constructor_project_returns: Default + IntoContextIter<Context = Self, Output = Id>;
    fn constructor_project(&mut self, arg0: Id, arg1: Id, returns: &mut Self::constructor_project_returns) -> ();
    type extractor_join_returns: Default + IntoContextIter<Context = Self, Output = (Id, Id, Id)>;
    fn extractor_join(&mut self, arg0: Id, returns: &mut Self::extractor_join_returns) -> ();
    type constructor_join_returns: Default + IntoContextIter<Context = Self, Output = Id>;
    fn constructor_join(&mut self, arg0: Id, arg1: Id, arg2: Id, returns: &mut Self::constructor_join_returns) -> ();
    type extractor_scan_returns: Default + IntoContextIter<Context = Self, Output = Id>;
    fn extractor_scan(&mut self, arg0: Id, returns: &mut Self::extractor_scan_returns) -> ();
    type constructor_scan_returns: Default + IntoContextIter<Context = Self, Output = Id>;
    fn constructor_scan(&mut self, arg0: Id, returns: &mut Self::constructor_scan_returns) -> ();
    type extractor_table_scan_returns: Default + IntoContextIter<Context = Self, Output = Id>;
    fn extractor_table_scan(&mut self, arg0: Id, returns: &mut Self::extractor_table_scan_returns) -> ();
    type constructor_table_scan_returns: Default + IntoContextIter<Context = Self, Output = Id>;
    fn constructor_table_scan(&mut self, arg0: Id, returns: &mut Self::constructor_table_scan_returns) -> ();
    type extractor_index_scan_returns: Default + IntoContextIter<Context = Self, Output = Id>;
    fn extractor_index_scan(&mut self, arg0: Id, returns: &mut Self::extractor_index_scan_returns) -> ();
    type constructor_index_scan_returns: Default + IntoContextIter<Context = Self, Output = Id>;
    fn constructor_index_scan(&mut self, arg0: Id, returns: &mut Self::constructor_index_scan_returns) -> ();
    type extractor_nested_loop_join_returns: Default + IntoContextIter<Context = Self, Output = (Id, Id, Id)>;
    fn extractor_nested_loop_join(&mut self, arg0: Id, returns: &mut Self::extractor_nested_loop_join_returns) -> ();
    type constructor_nested_loop_join_returns: Default + IntoContextIter<Context = Self, Output = Id>;
    fn constructor_nested_loop_join(&mut self, arg0: Id, arg1: Id, arg2: Id, returns: &mut Self::constructor_nested_loop_join_returns) -> ();
    type extractor_hash_join_returns: Default + IntoContextIter<Context = Self, Output = (Id, Id, Id)>;
    fn extractor_hash_join(&mut self, arg0: Id, returns: &mut Self::extractor_hash_join_returns) -> ();
    type constructor_hash_join_returns: Default + IntoContextIter<Context = Self, Output = Id>;
    fn constructor_hash_join(&mut self, arg0: Id, arg1: Id, arg2: Id, returns: &mut Self::constructor_hash_join_returns) -> ();
    type extractor_merge_join_returns: Default + IntoContextIter<Context = Self, Output = (Id, Id, Id)>;
    fn extractor_merge_join(&mut self, arg0: Id, returns: &mut Self::extractor_merge_join_returns) -> ();
    type constructor_merge_join_returns: Default + IntoContextIter<Context = Self, Output = Id>;
    fn constructor_merge_join(&mut self, arg0: Id, arg1: Id, arg2: Id, returns: &mut Self::constructor_merge_join_returns) -> ();
    type extractor_sort_returns: Default + IntoContextIter<Context = Self, Output = (Id, Id)>;
    fn extractor_sort(&mut self, arg0: Id, returns: &mut Self::extractor_sort_returns) -> ();
    type constructor_sort_returns: Default + IntoContextIter<Context = Self, Output = Id>;
    fn constructor_sort(&mut self, arg0: Id, arg1: Id, returns: &mut Self::constructor_sort_returns) -> ();
    type extractor_explore_returns: Default + IntoContextIter<Context = Self, Output = Id>;
    fn extractor_explore(&mut self, arg0: Id, returns: &mut Self::extractor_explore_returns) -> ();
}

pub trait ContextIter {
    type Context;
    type Output;
    fn next(&mut self, ctx: &mut Self::Context) -> Option<Self::Output>;
    fn size_hint(&self) -> (usize, Option<usize>) { (0, None) }
}

pub trait IntoContextIter {
    type Context;
    type Output;
    type IntoIter: ContextIter<Context = Self::Context, Output = Self::Output>;
    fn into_context_iter(self) -> Self::IntoIter;
}

pub trait Length {
    fn len(&self) -> usize;
}

impl<T> Length for std::vec::Vec<T> {
    fn len(&self) -> usize {
        std::vec::Vec::len(self)
    }
}

pub struct ContextIterWrapper<I, C> {
    iter: I,
    _ctx: std::marker::PhantomData<C>,
}
impl<I: Default, C> Default for ContextIterWrapper<I, C> {
    fn default() -> Self {
        ContextIterWrapper {
            iter: I::default(),
            _ctx: std::marker::PhantomData
        }
    }
}
impl<I, C> std::ops::Deref for ContextIterWrapper<I, C> {
    type Target = I;
    fn deref(&self) -> &I {
        &self.iter
    }
}
impl<I, C> std::ops::DerefMut for ContextIterWrapper<I, C> {
    fn deref_mut(&mut self) -> &mut I {
        &mut self.iter
    }
}
impl<I: Iterator, C: Context> From<I> for ContextIterWrapper<I, C> {
    fn from(iter: I) -> Self {
        Self { iter, _ctx: std::marker::PhantomData }
    }
}
impl<I: Iterator, C: Context> ContextIter for ContextIterWrapper<I, C> {
    type Context = C;
    type Output = I::Item;
    fn next(&mut self, _ctx: &mut Self::Context) -> Option<Self::Output> {
        self.iter.next()
    }
    fn size_hint(&self) -> (usize, Option<usize>) {
        self.iter.size_hint()
    }
}
impl<I: IntoIterator, C: Context> IntoContextIter for ContextIterWrapper<I, C> {
    type Context = C;
    type Output = I::Item;
    type IntoIter = ContextIterWrapper<I::IntoIter, C>;
    fn into_context_iter(self) -> Self::IntoIter {
        ContextIterWrapper {
            iter: self.iter.into_iter(),
            _ctx: std::marker::PhantomData
        }
    }
}
impl<T, E: Extend<T>, C> Extend<T> for ContextIterWrapper<E, C> {
    fn extend<I: IntoIterator<Item = T>>(&mut self, iter: I) {
        self.iter.extend(iter);
    }
}
impl<L: Length, C> Length for ContextIterWrapper<L, C> {
    fn len(&self) -> usize {
        self.iter.len()
    }
}
           

/// Internal type value: defined at examples/database_optimizer/isle/rules.isle line 14.
#[derive(Clone, Debug)]
pub enum value {
    Int {
        val: i64,
    },
    Str {
        val: String,
    },
    Bool {
        val: bool,
    },
}

// Generated as internal constructor for term explore.
pub fn constructor_explore<C: Context>(
    ctx: &mut C,
    arg0: Id,
    returns: &mut (impl Extend<Id> + Length),
) -> () {
    let mut v15 = C::extractor_mul_returns::default();
    C::extractor_mul(ctx, arg0, &mut v15);
    let mut v15 = v15.into_context_iter();
    while let Some(v16) = v15.next(ctx) {
        let mut v91 = C::extractor_const_val_returns::default();
        &C::extractor_const_val(ctx, v16.1, &mut v91);
        let mut v91 = v91.into_context_iter();
        while let Some(v92) = v91.next(ctx) {
            if let &value::Int {
                val: v93,
            } = &v92 {
                match v93 {
                    0_i64 => {
                        let v95 = value::Int {
                            val: 0_i64,
                        };
                        let mut v96 = C::constructor_const_val_returns::default();
                        C::constructor_const_val(ctx, &v95, &mut v96);
                        let mut v96 = v96.into_context_iter();
                        while let Some(v97) = v96.next(ctx) {
                            // Rule at examples/database_optimizer/isle/rules.isle line 307.
                            returns.extend(Some(v97));
                            if returns.len() >= MAX_ISLE_RETURNS { return; }
                        }
                    }
                    1_i64 => {
                        // Rule at examples/database_optimizer/isle/rules.isle line 301.
                        returns.extend(Some(v16.0));
                        if returns.len() >= MAX_ISLE_RETURNS { return; }
                    }
                    _ => {}
                }
            }
        }
        let mut v19 = C::constructor_mul_returns::default();
        C::constructor_mul(ctx, v16.1, v16.0, &mut v19);
        let mut v19 = v19.into_context_iter();
        while let Some(v20) = v19.next(ctx) {
            // Rule at examples/database_optimizer/isle/rules.isle line 212.
            returns.extend(Some(v20));
            if returns.len() >= MAX_ISLE_RETURNS { return; }
        }
        let mut v21 = C::extractor_mul_returns::default();
        C::extractor_mul(ctx, v16.1, &mut v21);
        let mut v21 = v21.into_context_iter();
        while let Some(v22) = v21.next(ctx) {
            let mut v25 = C::constructor_mul_returns::default();
            C::constructor_mul(ctx, v16.0, v22.0, &mut v25);
            let mut v25 = v25.into_context_iter();
            while let Some(v26) = v25.next(ctx) {
                let mut v27 = C::constructor_mul_returns::default();
                C::constructor_mul(ctx, v26, v22.1, &mut v27);
                let mut v27 = v27.into_context_iter();
                while let Some(v28) = v27.next(ctx) {
                    // Rule at examples/database_optimizer/isle/rules.isle line 218.
                    returns.extend(Some(v28));
                    if returns.len() >= MAX_ISLE_RETURNS { return; }
                }
            }
        }
        let mut v29 = C::extractor_add_returns::default();
        C::extractor_add(ctx, v16.1, &mut v29);
        let mut v29 = v29.into_context_iter();
        while let Some(v30) = v29.next(ctx) {
            let mut v33 = C::constructor_mul_returns::default();
            C::constructor_mul(ctx, v16.0, v30.0, &mut v33);
            let mut v33 = v33.into_context_iter();
            while let Some(v34) = v33.next(ctx) {
                let mut v35 = C::constructor_mul_returns::default();
                C::constructor_mul(ctx, v16.0, v30.1, &mut v35);
                let mut v35 = v35.into_context_iter();
                while let Some(v36) = v35.next(ctx) {
                    let mut v37 = C::constructor_add_returns::default();
                    C::constructor_add(ctx, v34, v36, &mut v37);
                    let mut v37 = v37.into_context_iter();
                    while let Some(v38) = v37.next(ctx) {
                        // Rule at examples/database_optimizer/isle/rules.isle line 224.
                        returns.extend(Some(v38));
                        if returns.len() >= MAX_ISLE_RETURNS { return; }
                    }
                }
            }
        }
    }
    let mut v45 = C::extractor_not_returns::default();
    C::extractor_not(ctx, arg0, &mut v45);
    let mut v45 = v45.into_context_iter();
    while let Some(v46) = v45.next(ctx) {
        let mut v123 = C::extractor_const_val_returns::default();
        &C::extractor_const_val(ctx, v46, &mut v123);
        let mut v123 = v123.into_context_iter();
        while let Some(v124) = v123.next(ctx) {
            if let &value::Bool {
                val: v125,
            } = &v124 {
                match v125 {
                    false => {
                        let v119 = true;
                        let v120 = value::Bool {
                            val: v119,
                        };
                        let mut v121 = C::constructor_const_val_returns::default();
                        C::constructor_const_val(ctx, &v120, &mut v121);
                        let mut v121 = v121.into_context_iter();
                        while let Some(v122) = v121.next(ctx) {
                            // Rule at examples/database_optimizer/isle/rules.isle line 360.
                            returns.extend(Some(v122));
                            if returns.len() >= MAX_ISLE_RETURNS { return; }
                        }
                    }
                    true => {
                        let v112 = false;
                        let v113 = value::Bool {
                            val: v112,
                        };
                        let mut v114 = C::constructor_const_val_returns::default();
                        C::constructor_const_val(ctx, &v113, &mut v114);
                        let mut v114 = v114.into_context_iter();
                        while let Some(v115) = v114.next(ctx) {
                            // Rule at examples/database_optimizer/isle/rules.isle line 355.
                            returns.extend(Some(v115));
                            if returns.len() >= MAX_ISLE_RETURNS { return; }
                        }
                    }
                    _ => {}
                }
            }
        }
        let mut v47 = C::constructor_not_returns::default();
        C::constructor_not(ctx, v46, &mut v47);
        let mut v47 = v47.into_context_iter();
        while let Some(v48) = v47.next(ctx) {
            let mut v49 = C::constructor_not_returns::default();
            C::constructor_not(ctx, v46, &mut v49);
            let mut v49 = v49.into_context_iter();
            while let Some(v50) = v49.next(ctx) {
                let mut v51 = C::constructor_or_returns::default();
                C::constructor_or(ctx, v48, v50, &mut v51);
                let mut v51 = v51.into_context_iter();
                while let Some(v52) = v51.next(ctx) {
                    // Rule at examples/database_optimizer/isle/rules.isle line 243.
                    returns.extend(Some(v52));
                    if returns.len() >= MAX_ISLE_RETURNS { return; }
                }
            }
        }
        let mut v53 = C::extractor_or_returns::default();
        C::extractor_or(ctx, v46, &mut v53);
        let mut v53 = v53.into_context_iter();
        while let Some(v54) = v53.next(ctx) {
            let mut v57 = C::constructor_not_returns::default();
            C::constructor_not(ctx, v54.0, &mut v57);
            let mut v57 = v57.into_context_iter();
            while let Some(v58) = v57.next(ctx) {
                let mut v59 = C::constructor_not_returns::default();
                C::constructor_not(ctx, v54.1, &mut v59);
                let mut v59 = v59.into_context_iter();
                while let Some(v60) = v59.next(ctx) {
                    let mut v61 = C::constructor_and_returns::default();
                    C::constructor_and(ctx, v58, v60, &mut v61);
                    let mut v61 = v61.into_context_iter();
                    while let Some(v62) = v61.next(ctx) {
                        // Rule at examples/database_optimizer/isle/rules.isle line 249.
                        returns.extend(Some(v62));
                        if returns.len() >= MAX_ISLE_RETURNS { return; }
                    }
                }
            }
        }
        let mut v63 = C::extractor_not_returns::default();
        C::extractor_not(ctx, v46, &mut v63);
        let mut v63 = v63.into_context_iter();
        while let Some(v64) = v63.next(ctx) {
            // Rule at examples/database_optimizer/isle/rules.isle line 255.
            returns.extend(Some(v64));
            if returns.len() >= MAX_ISLE_RETURNS { return; }
        }
    }
    let mut v65 = C::extractor_join_returns::default();
    C::extractor_join(ctx, arg0, &mut v65);
    let mut v65 = v65.into_context_iter();
    while let Some(v66) = v65.next(ctx) {
        let mut v70 = C::constructor_join_returns::default();
        C::constructor_join(ctx, v66.1, v66.0, v66.2, &mut v70);
        let mut v70 = v70.into_context_iter();
        while let Some(v71) = v70.next(ctx) {
            // Rule at examples/database_optimizer/isle/rules.isle line 273.
            returns.extend(Some(v71));
            if returns.len() >= MAX_ISLE_RETURNS { return; }
        }
        let mut v72 = C::extractor_join_returns::default();
        C::extractor_join(ctx, v66.1, &mut v72);
        let mut v72 = v72.into_context_iter();
        while let Some(v73) = v72.next(ctx) {
            let mut v77 = C::constructor_join_returns::default();
            C::constructor_join(ctx, v66.0, v73.0, v66.2, &mut v77);
            let mut v77 = v77.into_context_iter();
            while let Some(v78) = v77.next(ctx) {
                let mut v79 = C::constructor_join_returns::default();
                C::constructor_join(ctx, v78, v73.1, v73.2, &mut v79);
                let mut v79 = v79.into_context_iter();
                while let Some(v80) = v79.next(ctx) {
                    // Rule at examples/database_optimizer/isle/rules.isle line 279.
                    returns.extend(Some(v80));
                    if returns.len() >= MAX_ISLE_RETURNS { return; }
                }
            }
        }
        let mut v205 = C::constructor_nested_loop_join_returns::default();
        C::constructor_nested_loop_join(ctx, v66.0, v66.1, v66.2, &mut v205);
        let mut v205 = v205.into_context_iter();
        while let Some(v206) = v205.next(ctx) {
            // Rule at examples/database_optimizer/isle/rules.isle line 444.
            returns.extend(Some(v206));
            if returns.len() >= MAX_ISLE_RETURNS { return; }
        }
        let mut v207 = C::constructor_hash_join_returns::default();
        C::constructor_hash_join(ctx, v66.0, v66.1, v66.2, &mut v207);
        let mut v207 = v207.into_context_iter();
        while let Some(v208) = v207.next(ctx) {
            // Rule at examples/database_optimizer/isle/rules.isle line 450.
            returns.extend(Some(v208));
            if returns.len() >= MAX_ISLE_RETURNS { return; }
        }
        let mut v209 = C::constructor_merge_join_returns::default();
        C::constructor_merge_join(ctx, v66.0, v66.1, v66.2, &mut v209);
        let mut v209 = v209.into_context_iter();
        while let Some(v210) = v209.next(ctx) {
            // Rule at examples/database_optimizer/isle/rules.isle line 456.
            returns.extend(Some(v210));
            if returns.len() >= MAX_ISLE_RETURNS { return; }
        }
    }
    let mut v39 = C::extractor_or_returns::default();
    C::extractor_or(ctx, arg0, &mut v39);
    let mut v39 = v39.into_context_iter();
    while let Some(v40) = v39.next(ctx) {
        let mut v116 = C::extractor_const_val_returns::default();
        &C::extractor_const_val(ctx, v40.1, &mut v116);
        let mut v116 = v116.into_context_iter();
        while let Some(v117) = v116.next(ctx) {
            if let &value::Bool {
                val: v118,
            } = &v117 {
                match v118 {
                    false => {
                        // Rule at examples/database_optimizer/isle/rules.isle line 349.
                        returns.extend(Some(v40.0));
                        if returns.len() >= MAX_ISLE_RETURNS { return; }
                    }
                    true => {
                        let v119 = true;
                        let v120 = value::Bool {
                            val: v119,
                        };
                        let mut v121 = C::constructor_const_val_returns::default();
                        C::constructor_const_val(ctx, &v120, &mut v121);
                        let mut v121 = v121.into_context_iter();
                        while let Some(v122) = v121.next(ctx) {
                            // Rule at examples/database_optimizer/isle/rules.isle line 343.
                            returns.extend(Some(v122));
                            if returns.len() >= MAX_ISLE_RETURNS { return; }
                        }
                    }
                    _ => {}
                }
            }
        }
        if v40.0 == v40.1 {
            // Rule at examples/database_optimizer/isle/rules.isle line 267.
            returns.extend(Some(v40.0));
            if returns.len() >= MAX_ISLE_RETURNS { return; }
        }
        let mut v43 = C::constructor_or_returns::default();
        C::constructor_or(ctx, v40.1, v40.0, &mut v43);
        let mut v43 = v43.into_context_iter();
        while let Some(v44) = v43.next(ctx) {
            // Rule at examples/database_optimizer/isle/rules.isle line 237.
            returns.extend(Some(v44));
            if returns.len() >= MAX_ISLE_RETURNS { return; }
        }
    }
    let v112 = false;
    let v113 = value::Bool {
        val: v112,
    };
    let mut v114 = C::constructor_const_val_returns::default();
    C::constructor_const_val(ctx, &v113, &mut v114);
    let mut v114 = v114.into_context_iter();
    while let Some(v115) = v114.next(ctx) {
        let mut v109 = C::extractor_const_val_returns::default();
        &C::extractor_const_val(ctx, arg0, &mut v109);
        let mut v109 = v109.into_context_iter();
        while let Some(v110) = v109.next(ctx) {
            if let &value::Bool {
                val: v111,
            } = &v110 {
                if v111 == false {
                    // Rule at examples/database_optimizer/isle/rules.isle line 337.
                    returns.extend(Some(v115));
                    if returns.len() >= MAX_ISLE_RETURNS { return; }
                }
            }
        }
        let mut v130 = C::extractor_ne_returns::default();
        C::extractor_ne(ctx, arg0, &mut v130);
        let mut v130 = v130.into_context_iter();
        while let Some(v131) = v130.next(ctx) {
            if v131.0 == v131.1 {
                // Rule at examples/database_optimizer/isle/rules.isle line 370.
                returns.extend(Some(v115));
                if returns.len() >= MAX_ISLE_RETURNS { return; }
            }
        }
        let mut v134 = C::extractor_lt_returns::default();
        C::extractor_lt(ctx, arg0, &mut v134);
        let mut v134 = v134.into_context_iter();
        while let Some(v135) = v134.next(ctx) {
            if v135.0 == v135.1 {
                // Rule at examples/database_optimizer/isle/rules.isle line 374.
                returns.extend(Some(v115));
                if returns.len() >= MAX_ISLE_RETURNS { return; }
            }
        }
        let mut v142 = C::extractor_gt_returns::default();
        C::extractor_gt(ctx, arg0, &mut v142);
        let mut v142 = v142.into_context_iter();
        while let Some(v143) = v142.next(ctx) {
            if v143.0 == v143.1 {
                // Rule at examples/database_optimizer/isle/rules.isle line 382.
                returns.extend(Some(v115));
                if returns.len() >= MAX_ISLE_RETURNS { return; }
            }
        }
    }
    let mut v1 = C::extractor_add_returns::default();
    C::extractor_add(ctx, arg0, &mut v1);
    let mut v1 = v1.into_context_iter();
    while let Some(v2) = v1.next(ctx) {
        let mut v5 = C::constructor_add_returns::default();
        C::constructor_add(ctx, v2.1, v2.0, &mut v5);
        let mut v5 = v5.into_context_iter();
        while let Some(v6) = v5.next(ctx) {
            // Rule at examples/database_optimizer/isle/rules.isle line 199.
            returns.extend(Some(v6));
            if returns.len() >= MAX_ISLE_RETURNS { return; }
        }
        let mut v7 = C::extractor_add_returns::default();
        C::extractor_add(ctx, v2.1, &mut v7);
        let mut v7 = v7.into_context_iter();
        while let Some(v8) = v7.next(ctx) {
            let mut v11 = C::constructor_add_returns::default();
            C::constructor_add(ctx, v2.0, v8.0, &mut v11);
            let mut v11 = v11.into_context_iter();
            while let Some(v12) = v11.next(ctx) {
                let mut v13 = C::constructor_add_returns::default();
                C::constructor_add(ctx, v12, v8.1, &mut v13);
                let mut v13 = v13.into_context_iter();
                while let Some(v14) = v13.next(ctx) {
                    // Rule at examples/database_optimizer/isle/rules.isle line 205.
                    returns.extend(Some(v14));
                    if returns.len() >= MAX_ISLE_RETURNS { return; }
                }
            }
        }
        let mut v81 = C::extractor_const_val_returns::default();
        &C::extractor_const_val(ctx, v2.1, &mut v81);
        let mut v81 = v81.into_context_iter();
        while let Some(v82) = v81.next(ctx) {
            if let &value::Int {
                val: v83,
            } = &v82 {
                if v83 == 0_i64 {
                    // Rule at examples/database_optimizer/isle/rules.isle line 289.
                    returns.extend(Some(v2.0));
                    if returns.len() >= MAX_ISLE_RETURNS { return; }
                }
            }
        }
    }
    let v119 = true;
    let v120 = value::Bool {
        val: v119,
    };
    let mut v121 = C::constructor_const_val_returns::default();
    C::constructor_const_val(ctx, &v120, &mut v121);
    let mut v121 = v121.into_context_iter();
    while let Some(v122) = v121.next(ctx) {
        let mut v126 = C::extractor_eq_returns::default();
        C::extractor_eq(ctx, arg0, &mut v126);
        let mut v126 = v126.into_context_iter();
        while let Some(v127) = v126.next(ctx) {
            if v127.0 == v127.1 {
                // Rule at examples/database_optimizer/isle/rules.isle line 366.
                returns.extend(Some(v122));
                if returns.len() >= MAX_ISLE_RETURNS { return; }
            }
        }
        let mut v138 = C::extractor_le_returns::default();
        C::extractor_le(ctx, arg0, &mut v138);
        let mut v138 = v138.into_context_iter();
        while let Some(v139) = v138.next(ctx) {
            if v139.0 == v139.1 {
                // Rule at examples/database_optimizer/isle/rules.isle line 378.
                returns.extend(Some(v122));
                if returns.len() >= MAX_ISLE_RETURNS { return; }
            }
        }
        let mut v146 = C::extractor_ge_returns::default();
        C::extractor_ge(ctx, arg0, &mut v146);
        let mut v146 = v146.into_context_iter();
        while let Some(v147) = v146.next(ctx) {
            if v147.0 == v147.1 {
                // Rule at examples/database_optimizer/isle/rules.isle line 386.
                returns.extend(Some(v122));
                if returns.len() >= MAX_ISLE_RETURNS { return; }
            }
        }
    }
    let mut v150 = C::extractor_select_returns::default();
    C::extractor_select(ctx, arg0, &mut v150);
    let mut v150 = v150.into_context_iter();
    while let Some(v151) = v150.next(ctx) {
        let mut v154 = C::extractor_project_returns::default();
        C::extractor_project(ctx, v151.0, &mut v154);
        let mut v154 = v154.into_context_iter();
        while let Some(v155) = v154.next(ctx) {
            let mut v158 = C::constructor_select_returns::default();
            C::constructor_select(ctx, v155.1, v151.1, &mut v158);
            let mut v158 = v158.into_context_iter();
            while let Some(v159) = v158.next(ctx) {
                let mut v160 = C::constructor_project_returns::default();
                C::constructor_project(ctx, v155.0, v159, &mut v160);
                let mut v160 = v160.into_context_iter();
                while let Some(v161) = v160.next(ctx) {
                    // Rule at examples/database_optimizer/isle/rules.isle line 396.
                    returns.extend(Some(v161));
                    if returns.len() >= MAX_ISLE_RETURNS { return; }
                }
            }
        }
        let mut v162 = C::extractor_join_returns::default();
        C::extractor_join(ctx, v151.0, &mut v162);
        let mut v162 = v162.into_context_iter();
        while let Some(v163) = v162.next(ctx) {
            let mut v167 = C::constructor_select_returns::default();
            C::constructor_select(ctx, v163.0, v151.1, &mut v167);
            let mut v167 = v167.into_context_iter();
            while let Some(v168) = v167.next(ctx) {
                let mut v169 = C::constructor_select_returns::default();
                C::constructor_select(ctx, v163.1, v151.1, &mut v169);
                let mut v169 = v169.into_context_iter();
                while let Some(v170) = v169.next(ctx) {
                    let mut v171 = C::constructor_join_returns::default();
                    C::constructor_join(ctx, v168, v170, v163.2, &mut v171);
                    let mut v171 = v171.into_context_iter();
                    while let Some(v172) = v171.next(ctx) {
                        // Rule at examples/database_optimizer/isle/rules.isle line 403.
                        returns.extend(Some(v172));
                        if returns.len() >= MAX_ISLE_RETURNS { return; }
                    }
                }
            }
        }
        let mut v173 = C::extractor_select_returns::default();
        C::extractor_select(ctx, v151.0, &mut v173);
        let mut v173 = v173.into_context_iter();
        while let Some(v174) = v173.next(ctx) {
            let mut v177 = C::constructor_and_returns::default();
            C::constructor_and(ctx, v174.1, v151.1, &mut v177);
            let mut v177 = v177.into_context_iter();
            while let Some(v178) = v177.next(ctx) {
                let mut v179 = C::constructor_select_returns::default();
                C::constructor_select(ctx, v174.0, v178, &mut v179);
                let mut v179 = v179.into_context_iter();
                while let Some(v180) = v179.next(ctx) {
                    // Rule at examples/database_optimizer/isle/rules.isle line 409.
                    returns.extend(Some(v180));
                    if returns.len() >= MAX_ISLE_RETURNS { return; }
                }
            }
        }
    }
    let mut v84 = C::extractor_sub_returns::default();
    C::extractor_sub(ctx, arg0, &mut v84);
    let mut v84 = v84.into_context_iter();
    while let Some(v85) = v84.next(ctx) {
        if v85.0 == v85.1 {
            let v95 = value::Int {
                val: 0_i64,
            };
            let mut v96 = C::constructor_const_val_returns::default();
            C::constructor_const_val(ctx, &v95, &mut v96);
            let mut v96 = v96.into_context_iter();
            while let Some(v97) = v96.next(ctx) {
                // Rule at examples/database_optimizer/isle/rules.isle line 325.
                returns.extend(Some(v97));
                if returns.len() >= MAX_ISLE_RETURNS { return; }
            }
        }
        let mut v88 = C::extractor_const_val_returns::default();
        &C::extractor_const_val(ctx, v85.1, &mut v88);
        let mut v88 = v88.into_context_iter();
        while let Some(v89) = v88.next(ctx) {
            if let &value::Int {
                val: v90,
            } = &v89 {
                if v90 == 0_i64 {
                    // Rule at examples/database_optimizer/isle/rules.isle line 295.
                    returns.extend(Some(v85.0));
                    if returns.len() >= MAX_ISLE_RETURNS { return; }
                }
            }
        }
    }
    let mut v98 = C::extractor_div_returns::default();
    C::extractor_div(ctx, arg0, &mut v98);
    let mut v98 = v98.into_context_iter();
    while let Some(v99) = v98.next(ctx) {
        if v99.0 == v99.1 {
            let v106 = value::Int {
                val: 1_i64,
            };
            let mut v107 = C::constructor_const_val_returns::default();
            C::constructor_const_val(ctx, &v106, &mut v107);
            let mut v107 = v107.into_context_iter();
            while let Some(v108) = v107.next(ctx) {
                // Rule at examples/database_optimizer/isle/rules.isle line 319.
                returns.extend(Some(v108));
                if returns.len() >= MAX_ISLE_RETURNS { return; }
            }
        }
        let mut v102 = C::extractor_const_val_returns::default();
        &C::extractor_const_val(ctx, v99.1, &mut v102);
        let mut v102 = v102.into_context_iter();
        while let Some(v103) = v102.next(ctx) {
            if let &value::Int {
                val: v104,
            } = &v103 {
                if v104 == 1_i64 {
                    // Rule at examples/database_optimizer/isle/rules.isle line 313.
                    returns.extend(Some(v99.0));
                    if returns.len() >= MAX_ISLE_RETURNS { return; }
                }
            }
        }
    }
    let mut v199 = C::extractor_scan_returns::default();
    C::extractor_scan(ctx, arg0, &mut v199);
    let mut v199 = v199.into_context_iter();
    while let Some(v200) = v199.next(ctx) {
        let mut v201 = C::constructor_table_scan_returns::default();
        C::constructor_table_scan(ctx, v200, &mut v201);
        let mut v201 = v201.into_context_iter();
        while let Some(v202) = v201.next(ctx) {
            // Rule at examples/database_optimizer/isle/rules.isle line 426.
            returns.extend(Some(v202));
            if returns.len() >= MAX_ISLE_RETURNS { return; }
        }
        let mut v203 = C::constructor_index_scan_returns::default();
        C::constructor_index_scan(ctx, v200, &mut v203);
        let mut v203 = v203.into_context_iter();
        while let Some(v204) = v203.next(ctx) {
            // Rule at examples/database_optimizer/isle/rules.isle line 435.
            returns.extend(Some(v204));
            if returns.len() >= MAX_ISLE_RETURNS { return; }
        }
    }
    let mut v109 = C::extractor_const_val_returns::default();
    &C::extractor_const_val(ctx, arg0, &mut v109);
    let mut v109 = v109.into_context_iter();
    while let Some(v110) = v109.next(ctx) {
        if let &value::Bool {
            val: v111,
        } = &v110 {
            if v111 == true {
                // Rule at examples/database_optimizer/isle/rules.isle line 331.
                returns.extend(Some(arg0));
                if returns.len() >= MAX_ISLE_RETURNS { return; }
            }
        }
    }
    let mut v181 = C::extractor_project_returns::default();
    C::extractor_project(ctx, arg0, &mut v181);
    let mut v181 = v181.into_context_iter();
    while let Some(v182) = v181.next(ctx) {
        let v185 = C::extractor_ref_colset(ctx, v182.0);
        if let Some(v186) = v185 {
            let mut v187 = C::extractor_project_returns::default();
            C::extractor_project(ctx, v182.1, &mut v187);
            let mut v187 = v187.into_context_iter();
            while let Some(v188) = v187.next(ctx) {
                let v191 = C::extractor_ref_colset(ctx, v188.0);
                if let Some(v192) = v191 {
                    let v193 = C::constructor_combine_columns(ctx, v192, v186);
                    if let Some(v194) = v193 {
                        let v195 = C::constructor_ref_colset(ctx, v194);
                        if let Some(v196) = v195 {
                            let mut v197 = C::constructor_project_returns::default();
                            C::constructor_project(ctx, v196, v188.1, &mut v197);
                            let mut v197 = v197.into_context_iter();
                            while let Some(v198) = v197.next(ctx) {
                                // Rule at examples/database_optimizer/isle/rules.isle line 415.
                                returns.extend(Some(v198));
                                if returns.len() >= MAX_ISLE_RETURNS { return; }
                            }
                        }
                    }
                }
            }
        }
    }
    // Rule at examples/database_optimizer/isle/rules.isle line 261.
    returns.extend(Some(arg0));
    if returns.len() >= MAX_ISLE_RETURNS { return; }
}
