// GENERATED BY ISLE. DO NOT EDIT!
//
// Generated automatically from the instruction-selection DSL code in:
// - examples/database_optimizer/isle/rules.isle

#![allow(dead_code, unreachable_code, unreachable_patterns)]
#![allow(unused_imports, unused_variables, non_snake_case, unused_mut)]
#![allow(irrefutable_let_patterns, unused_assignments, non_camel_case_types)]

use super::*;  // Pulls in all external types.
use std::marker::PhantomData;

/// Context during lowering: an implementation of this trait
/// must be provided with all external constructors and extractors.
/// A mutable borrow is passed along through all lowering logic.
pub trait Context {
    fn extractor_const_val(&mut self, arg0: Id) -> Option<value>;
    fn constructor_const_val(&mut self, arg0: &value) -> Id;
    fn extractor_access_table(&mut self, arg0: Id) -> Option<usize>;
    fn constructor_access_table(&mut self, arg0: usize) -> Option<Id>;
    fn extractor_access_index(&mut self, arg0: Id) -> Option<usize>;
    fn constructor_access_index(&mut self, arg0: usize) -> Option<Id>;
    fn extractor_ref_colset(&mut self, arg0: Id) -> Option<usize>;
    fn constructor_ref_colset(&mut self, arg0: usize) -> Option<Id>;
    fn extractor_combine_columns(&mut self, arg0: usize) -> Option<(usize, usize)>;
    fn constructor_combine_columns(&mut self, arg0: usize, arg1: usize) -> Option<usize>;
    fn extractor_add(&mut self, arg0: Id) -> Option<(Id, Id)>;
    fn constructor_add(&mut self, arg0: Id, arg1: Id) -> Id;
    fn extractor_sub(&mut self, arg0: Id) -> Option<(Id, Id)>;
    fn constructor_sub(&mut self, arg0: Id, arg1: Id) -> Id;
    fn extractor_mul(&mut self, arg0: Id) -> Option<(Id, Id)>;
    fn constructor_mul(&mut self, arg0: Id, arg1: Id) -> Id;
    fn extractor_div(&mut self, arg0: Id) -> Option<(Id, Id)>;
    fn constructor_div(&mut self, arg0: Id, arg1: Id) -> Id;
    fn extractor_eq(&mut self, arg0: Id) -> Option<(Id, Id)>;
    fn constructor_eq(&mut self, arg0: Id, arg1: Id) -> Id;
    fn extractor_lt(&mut self, arg0: Id) -> Option<(Id, Id)>;
    fn constructor_lt(&mut self, arg0: Id, arg1: Id) -> Id;
    fn extractor_gt(&mut self, arg0: Id) -> Option<(Id, Id)>;
    fn constructor_gt(&mut self, arg0: Id, arg1: Id) -> Id;
    fn extractor_le(&mut self, arg0: Id) -> Option<(Id, Id)>;
    fn constructor_le(&mut self, arg0: Id, arg1: Id) -> Id;
    fn extractor_ge(&mut self, arg0: Id) -> Option<(Id, Id)>;
    fn constructor_ge(&mut self, arg0: Id, arg1: Id) -> Id;
    fn extractor_ne(&mut self, arg0: Id) -> Option<(Id, Id)>;
    fn constructor_ne(&mut self, arg0: Id, arg1: Id) -> Id;
    fn extractor_and(&mut self, arg0: Id) -> Option<(Id, Id)>;
    fn constructor_and(&mut self, arg0: Id, arg1: Id) -> Id;
    fn extractor_or(&mut self, arg0: Id) -> Option<(Id, Id)>;
    fn constructor_or(&mut self, arg0: Id, arg1: Id) -> Id;
    fn extractor_not(&mut self, arg0: Id) -> Option<Id>;
    fn constructor_not(&mut self, arg0: Id) -> Id;
    fn extractor_select(&mut self, arg0: Id) -> Option<(Id, Id)>;
    fn constructor_select(&mut self, arg0: Id, arg1: Id) -> Id;
    fn extractor_project(&mut self, arg0: Id) -> Option<(Id, Id)>;
    fn constructor_project(&mut self, arg0: Id, arg1: Id) -> Id;
    fn extractor_join(&mut self, arg0: Id) -> Option<(Id, Id, Id)>;
    fn constructor_join(&mut self, arg0: Id, arg1: Id, arg2: Id) -> Id;
    fn extractor_scan(&mut self, arg0: Id) -> Option<Id>;
    fn constructor_scan(&mut self, arg0: Id) -> Id;
    fn extractor_table_scan(&mut self, arg0: Id) -> Option<Id>;
    fn constructor_table_scan(&mut self, arg0: Id) -> Id;
    fn extractor_index_scan(&mut self, arg0: Id) -> Option<Id>;
    fn constructor_index_scan(&mut self, arg0: Id) -> Id;
    fn extractor_nested_loop_join(&mut self, arg0: Id) -> Option<(Id, Id, Id)>;
    fn constructor_nested_loop_join(&mut self, arg0: Id, arg1: Id, arg2: Id) -> Id;
    fn extractor_hash_join(&mut self, arg0: Id) -> Option<(Id, Id, Id)>;
    fn constructor_hash_join(&mut self, arg0: Id, arg1: Id, arg2: Id) -> Id;
    fn extractor_merge_join(&mut self, arg0: Id) -> Option<(Id, Id, Id)>;
    fn constructor_merge_join(&mut self, arg0: Id, arg1: Id, arg2: Id) -> Id;
    fn extractor_sort(&mut self, arg0: Id) -> Option<(Id, Id)>;
    fn constructor_sort(&mut self, arg0: Id, arg1: Id) -> Id;
    type extractor_explore_returns: Default + IntoContextIter<Context = Self, Output = Id>;
    fn extractor_explore(&mut self, arg0: Id, returns: &mut Self::extractor_explore_returns) -> ();
}

pub trait ContextIter {
    type Context;
    type Output;
    fn next(&mut self, ctx: &mut Self::Context) -> Option<Self::Output>;
    fn size_hint(&self) -> (usize, Option<usize>) { (0, None) }
}

pub trait IntoContextIter {
    type Context;
    type Output;
    type IntoIter: ContextIter<Context = Self::Context, Output = Self::Output>;
    fn into_context_iter(self) -> Self::IntoIter;
}

pub trait Length {
    fn len(&self) -> usize;
}

impl<T> Length for std::vec::Vec<T> {
    fn len(&self) -> usize {
        std::vec::Vec::len(self)
    }
}

pub struct ContextIterWrapper<I, C> {
    iter: I,
    _ctx: std::marker::PhantomData<C>,
}
impl<I: Default, C> Default for ContextIterWrapper<I, C> {
    fn default() -> Self {
        ContextIterWrapper {
            iter: I::default(),
            _ctx: std::marker::PhantomData
        }
    }
}
impl<I, C> std::ops::Deref for ContextIterWrapper<I, C> {
    type Target = I;
    fn deref(&self) -> &I {
        &self.iter
    }
}
impl<I, C> std::ops::DerefMut for ContextIterWrapper<I, C> {
    fn deref_mut(&mut self) -> &mut I {
        &mut self.iter
    }
}
impl<I: Iterator, C: Context> From<I> for ContextIterWrapper<I, C> {
    fn from(iter: I) -> Self {
        Self { iter, _ctx: std::marker::PhantomData }
    }
}
impl<I: Iterator, C: Context> ContextIter for ContextIterWrapper<I, C> {
    type Context = C;
    type Output = I::Item;
    fn next(&mut self, _ctx: &mut Self::Context) -> Option<Self::Output> {
        self.iter.next()
    }
    fn size_hint(&self) -> (usize, Option<usize>) {
        self.iter.size_hint()
    }
}
impl<I: IntoIterator, C: Context> IntoContextIter for ContextIterWrapper<I, C> {
    type Context = C;
    type Output = I::Item;
    type IntoIter = ContextIterWrapper<I::IntoIter, C>;
    fn into_context_iter(self) -> Self::IntoIter {
        ContextIterWrapper {
            iter: self.iter.into_iter(),
            _ctx: std::marker::PhantomData
        }
    }
}
impl<T, E: Extend<T>, C> Extend<T> for ContextIterWrapper<E, C> {
    fn extend<I: IntoIterator<Item = T>>(&mut self, iter: I) {
        self.iter.extend(iter);
    }
}
impl<L: Length, C> Length for ContextIterWrapper<L, C> {
    fn len(&self) -> usize {
        self.iter.len()
    }
}
           

/// Internal type value: defined at examples/database_optimizer/isle/rules.isle line 14.
#[derive(Clone, Debug)]
pub enum value {
    Int {
        val: i64,
    },
    Str {
        val: String,
    },
    Bool {
        val: bool,
    },
}

// Generated as internal constructor for term explore.
pub fn constructor_explore<C: Context>(
    ctx: &mut C,
    arg0: Id,
    returns: &mut (impl Extend<Id> + Length),
) -> () {
    let v12 = C::extractor_mul(ctx, arg0);
    if let Some(v13) = v12 {
        let v72 = &C::extractor_const_val(ctx, v13.1);
        if let Some(v73) = v72 {
            if let &value::Int {
                val: v74,
            } = v73 {
                match v74 {
                    0_i64 => {
                        let v76 = value::Int {
                            val: 0_i64,
                        };
                        let v77 = C::constructor_const_val(ctx, &v76);
                        // Rule at examples/database_optimizer/isle/rules.isle line 307.
                        returns.extend(Some(v77));
                        if returns.len() >= MAX_ISLE_RETURNS { return; }
                    }
                    1_i64 => {
                        // Rule at examples/database_optimizer/isle/rules.isle line 301.
                        returns.extend(Some(v13.0));
                        if returns.len() >= MAX_ISLE_RETURNS { return; }
                    }
                    _ => {}
                }
            }
        }
        let v17 = C::extractor_mul(ctx, v13.1);
        if let Some(v18) = v17 {
            let v21 = C::constructor_mul(ctx, v13.0, v18.0);
            let v22 = C::constructor_mul(ctx, v21, v18.1);
            // Rule at examples/database_optimizer/isle/rules.isle line 218.
            returns.extend(Some(v22));
            if returns.len() >= MAX_ISLE_RETURNS { return; }
        }
        let v23 = C::extractor_add(ctx, v13.1);
        if let Some(v24) = v23 {
            let v27 = C::constructor_mul(ctx, v13.0, v24.0);
            let v28 = C::constructor_mul(ctx, v13.0, v24.1);
            let v29 = C::constructor_add(ctx, v27, v28);
            // Rule at examples/database_optimizer/isle/rules.isle line 224.
            returns.extend(Some(v29));
            if returns.len() >= MAX_ISLE_RETURNS { return; }
        }
        let v16 = C::constructor_mul(ctx, v13.1, v13.0);
        // Rule at examples/database_optimizer/isle/rules.isle line 212.
        returns.extend(Some(v16));
        if returns.len() >= MAX_ISLE_RETURNS { return; }
    }
    let v35 = C::extractor_not(ctx, arg0);
    if let Some(v36) = v35 {
        let v100 = &C::extractor_const_val(ctx, v36);
        if let Some(v101) = v100 {
            if let &value::Bool {
                val: v102,
            } = v101 {
                match v102 {
                    false => {
                        let v97 = true;
                        let v98 = value::Bool {
                            val: v97,
                        };
                        let v99 = C::constructor_const_val(ctx, &v98);
                        // Rule at examples/database_optimizer/isle/rules.isle line 360.
                        returns.extend(Some(v99));
                        if returns.len() >= MAX_ISLE_RETURNS { return; }
                    }
                    true => {
                        let v91 = false;
                        let v92 = value::Bool {
                            val: v91,
                        };
                        let v93 = C::constructor_const_val(ctx, &v92);
                        // Rule at examples/database_optimizer/isle/rules.isle line 355.
                        returns.extend(Some(v93));
                        if returns.len() >= MAX_ISLE_RETURNS { return; }
                    }
                    _ => {}
                }
            }
        }
        let v40 = C::extractor_or(ctx, v36);
        if let Some(v41) = v40 {
            let v44 = C::constructor_not(ctx, v41.0);
            let v45 = C::constructor_not(ctx, v41.1);
            let v46 = C::constructor_and(ctx, v44, v45);
            // Rule at examples/database_optimizer/isle/rules.isle line 249.
            returns.extend(Some(v46));
            if returns.len() >= MAX_ISLE_RETURNS { return; }
        }
        let v47 = C::extractor_not(ctx, v36);
        if let Some(v48) = v47 {
            // Rule at examples/database_optimizer/isle/rules.isle line 255.
            returns.extend(Some(v48));
            if returns.len() >= MAX_ISLE_RETURNS { return; }
        }
        let v37 = C::constructor_not(ctx, v36);
        let v38 = C::constructor_not(ctx, v36);
        let v39 = C::constructor_or(ctx, v37, v38);
        // Rule at examples/database_optimizer/isle/rules.isle line 243.
        returns.extend(Some(v39));
        if returns.len() >= MAX_ISLE_RETURNS { return; }
    }
    let v49 = C::extractor_join(ctx, arg0);
    if let Some(v50) = v49 {
        let v55 = C::extractor_join(ctx, v50.1);
        if let Some(v56) = v55 {
            let v60 = C::constructor_join(ctx, v50.0, v56.0, v50.2);
            let v61 = C::constructor_join(ctx, v60, v56.1, v56.2);
            // Rule at examples/database_optimizer/isle/rules.isle line 279.
            returns.extend(Some(v61));
            if returns.len() >= MAX_ISLE_RETURNS { return; }
        }
        let v54 = C::constructor_join(ctx, v50.1, v50.0, v50.2);
        // Rule at examples/database_optimizer/isle/rules.isle line 273.
        returns.extend(Some(v54));
        if returns.len() >= MAX_ISLE_RETURNS { return; }
        let v172 = C::constructor_nested_loop_join(ctx, v50.0, v50.1, v50.2);
        // Rule at examples/database_optimizer/isle/rules.isle line 444.
        returns.extend(Some(v172));
        if returns.len() >= MAX_ISLE_RETURNS { return; }
        let v173 = C::constructor_hash_join(ctx, v50.0, v50.1, v50.2);
        // Rule at examples/database_optimizer/isle/rules.isle line 450.
        returns.extend(Some(v173));
        if returns.len() >= MAX_ISLE_RETURNS { return; }
        let v174 = C::constructor_merge_join(ctx, v50.0, v50.1, v50.2);
        // Rule at examples/database_optimizer/isle/rules.isle line 456.
        returns.extend(Some(v174));
        if returns.len() >= MAX_ISLE_RETURNS { return; }
    }
    let v30 = C::extractor_or(ctx, arg0);
    if let Some(v31) = v30 {
        let v94 = &C::extractor_const_val(ctx, v31.1);
        if let Some(v95) = v94 {
            if let &value::Bool {
                val: v96,
            } = v95 {
                match v96 {
                    false => {
                        // Rule at examples/database_optimizer/isle/rules.isle line 349.
                        returns.extend(Some(v31.0));
                        if returns.len() >= MAX_ISLE_RETURNS { return; }
                    }
                    true => {
                        let v97 = true;
                        let v98 = value::Bool {
                            val: v97,
                        };
                        let v99 = C::constructor_const_val(ctx, &v98);
                        // Rule at examples/database_optimizer/isle/rules.isle line 343.
                        returns.extend(Some(v99));
                        if returns.len() >= MAX_ISLE_RETURNS { return; }
                    }
                    _ => {}
                }
            }
        }
        if v31.0 == v31.1 {
            // Rule at examples/database_optimizer/isle/rules.isle line 267.
            returns.extend(Some(v31.0));
            if returns.len() >= MAX_ISLE_RETURNS { return; }
        }
        let v34 = C::constructor_or(ctx, v31.1, v31.0);
        // Rule at examples/database_optimizer/isle/rules.isle line 237.
        returns.extend(Some(v34));
        if returns.len() >= MAX_ISLE_RETURNS { return; }
    }
    let v1 = C::extractor_add(ctx, arg0);
    if let Some(v2) = v1 {
        let v6 = C::extractor_add(ctx, v2.1);
        if let Some(v7) = v6 {
            let v10 = C::constructor_add(ctx, v2.0, v7.0);
            let v11 = C::constructor_add(ctx, v10, v7.1);
            // Rule at examples/database_optimizer/isle/rules.isle line 205.
            returns.extend(Some(v11));
            if returns.len() >= MAX_ISLE_RETURNS { return; }
        }
        let v62 = &C::extractor_const_val(ctx, v2.1);
        if let Some(v63) = v62 {
            if let &value::Int {
                val: v64,
            } = v63 {
                if v64 == 0_i64 {
                    // Rule at examples/database_optimizer/isle/rules.isle line 289.
                    returns.extend(Some(v2.0));
                    if returns.len() >= MAX_ISLE_RETURNS { return; }
                }
            }
        }
        let v5 = C::constructor_add(ctx, v2.1, v2.0);
        // Rule at examples/database_optimizer/isle/rules.isle line 199.
        returns.extend(Some(v5));
        if returns.len() >= MAX_ISLE_RETURNS { return; }
    }
    let v127 = C::extractor_select(ctx, arg0);
    if let Some(v128) = v127 {
        let v131 = C::extractor_project(ctx, v128.0);
        if let Some(v132) = v131 {
            let v135 = C::constructor_select(ctx, v132.1, v128.1);
            let v136 = C::constructor_project(ctx, v132.0, v135);
            // Rule at examples/database_optimizer/isle/rules.isle line 396.
            returns.extend(Some(v136));
            if returns.len() >= MAX_ISLE_RETURNS { return; }
        }
        let v137 = C::extractor_join(ctx, v128.0);
        if let Some(v138) = v137 {
            let v142 = C::constructor_select(ctx, v138.0, v128.1);
            let v143 = C::constructor_select(ctx, v138.1, v128.1);
            let v144 = C::constructor_join(ctx, v142, v143, v138.2);
            // Rule at examples/database_optimizer/isle/rules.isle line 403.
            returns.extend(Some(v144));
            if returns.len() >= MAX_ISLE_RETURNS { return; }
        }
        let v145 = C::extractor_select(ctx, v128.0);
        if let Some(v146) = v145 {
            let v149 = C::constructor_and(ctx, v146.1, v128.1);
            let v150 = C::constructor_select(ctx, v146.0, v149);
            // Rule at examples/database_optimizer/isle/rules.isle line 409.
            returns.extend(Some(v150));
            if returns.len() >= MAX_ISLE_RETURNS { return; }
        }
    }
    let v65 = C::extractor_sub(ctx, arg0);
    if let Some(v66) = v65 {
        let v69 = &C::extractor_const_val(ctx, v66.1);
        if let Some(v70) = v69 {
            if let &value::Int {
                val: v71,
            } = v70 {
                if v71 == 0_i64 {
                    // Rule at examples/database_optimizer/isle/rules.isle line 295.
                    returns.extend(Some(v66.0));
                    if returns.len() >= MAX_ISLE_RETURNS { return; }
                }
            }
        }
        if v66.0 == v66.1 {
            let v76 = value::Int {
                val: 0_i64,
            };
            let v77 = C::constructor_const_val(ctx, &v76);
            // Rule at examples/database_optimizer/isle/rules.isle line 325.
            returns.extend(Some(v77));
            if returns.len() >= MAX_ISLE_RETURNS { return; }
        }
    }
    let v78 = C::extractor_div(ctx, arg0);
    if let Some(v79) = v78 {
        let v82 = &C::extractor_const_val(ctx, v79.1);
        if let Some(v83) = v82 {
            if let &value::Int {
                val: v84,
            } = v83 {
                if v84 == 1_i64 {
                    // Rule at examples/database_optimizer/isle/rules.isle line 313.
                    returns.extend(Some(v79.0));
                    if returns.len() >= MAX_ISLE_RETURNS { return; }
                }
            }
        }
        if v79.0 == v79.1 {
            let v86 = value::Int {
                val: 1_i64,
            };
            let v87 = C::constructor_const_val(ctx, &v86);
            // Rule at examples/database_optimizer/isle/rules.isle line 319.
            returns.extend(Some(v87));
            if returns.len() >= MAX_ISLE_RETURNS { return; }
        }
    }
    let v88 = &C::extractor_const_val(ctx, arg0);
    if let Some(v89) = v88 {
        if let &value::Bool {
            val: v90,
        } = v89 {
            match v90 {
                false => {
                    let v91 = false;
                    let v92 = value::Bool {
                        val: v91,
                    };
                    let v93 = C::constructor_const_val(ctx, &v92);
                    // Rule at examples/database_optimizer/isle/rules.isle line 337.
                    returns.extend(Some(v93));
                    if returns.len() >= MAX_ISLE_RETURNS { return; }
                }
                true => {
                    // Rule at examples/database_optimizer/isle/rules.isle line 331.
                    returns.extend(Some(arg0));
                    if returns.len() >= MAX_ISLE_RETURNS { return; }
                }
                _ => {}
            }
        }
    }
    let v168 = C::extractor_scan(ctx, arg0);
    if let Some(v169) = v168 {
        let v170 = C::constructor_table_scan(ctx, v169);
        // Rule at examples/database_optimizer/isle/rules.isle line 426.
        returns.extend(Some(v170));
        if returns.len() >= MAX_ISLE_RETURNS { return; }
        let v171 = C::constructor_index_scan(ctx, v169);
        // Rule at examples/database_optimizer/isle/rules.isle line 435.
        returns.extend(Some(v171));
        if returns.len() >= MAX_ISLE_RETURNS { return; }
    }
    let v103 = C::extractor_eq(ctx, arg0);
    if let Some(v104) = v103 {
        if v104.0 == v104.1 {
            let v97 = true;
            let v98 = value::Bool {
                val: v97,
            };
            let v99 = C::constructor_const_val(ctx, &v98);
            // Rule at examples/database_optimizer/isle/rules.isle line 366.
            returns.extend(Some(v99));
            if returns.len() >= MAX_ISLE_RETURNS { return; }
        }
    }
    let v107 = C::extractor_ne(ctx, arg0);
    if let Some(v108) = v107 {
        if v108.0 == v108.1 {
            let v91 = false;
            let v92 = value::Bool {
                val: v91,
            };
            let v93 = C::constructor_const_val(ctx, &v92);
            // Rule at examples/database_optimizer/isle/rules.isle line 370.
            returns.extend(Some(v93));
            if returns.len() >= MAX_ISLE_RETURNS { return; }
        }
    }
    let v111 = C::extractor_lt(ctx, arg0);
    if let Some(v112) = v111 {
        if v112.0 == v112.1 {
            let v91 = false;
            let v92 = value::Bool {
                val: v91,
            };
            let v93 = C::constructor_const_val(ctx, &v92);
            // Rule at examples/database_optimizer/isle/rules.isle line 374.
            returns.extend(Some(v93));
            if returns.len() >= MAX_ISLE_RETURNS { return; }
        }
    }
    let v115 = C::extractor_le(ctx, arg0);
    if let Some(v116) = v115 {
        if v116.0 == v116.1 {
            let v97 = true;
            let v98 = value::Bool {
                val: v97,
            };
            let v99 = C::constructor_const_val(ctx, &v98);
            // Rule at examples/database_optimizer/isle/rules.isle line 378.
            returns.extend(Some(v99));
            if returns.len() >= MAX_ISLE_RETURNS { return; }
        }
    }
    let v119 = C::extractor_gt(ctx, arg0);
    if let Some(v120) = v119 {
        if v120.0 == v120.1 {
            let v91 = false;
            let v92 = value::Bool {
                val: v91,
            };
            let v93 = C::constructor_const_val(ctx, &v92);
            // Rule at examples/database_optimizer/isle/rules.isle line 382.
            returns.extend(Some(v93));
            if returns.len() >= MAX_ISLE_RETURNS { return; }
        }
    }
    let v123 = C::extractor_ge(ctx, arg0);
    if let Some(v124) = v123 {
        if v124.0 == v124.1 {
            let v97 = true;
            let v98 = value::Bool {
                val: v97,
            };
            let v99 = C::constructor_const_val(ctx, &v98);
            // Rule at examples/database_optimizer/isle/rules.isle line 386.
            returns.extend(Some(v99));
            if returns.len() >= MAX_ISLE_RETURNS { return; }
        }
    }
    let v151 = C::extractor_project(ctx, arg0);
    if let Some(v152) = v151 {
        let v155 = C::extractor_ref_colset(ctx, v152.0);
        if let Some(v156) = v155 {
            let v157 = C::extractor_project(ctx, v152.1);
            if let Some(v158) = v157 {
                let v161 = C::extractor_ref_colset(ctx, v158.0);
                if let Some(v162) = v161 {
                    let v163 = C::constructor_combine_columns(ctx, v162, v156);
                    if let Some(v164) = v163 {
                        let v165 = C::constructor_ref_colset(ctx, v164);
                        if let Some(v166) = v165 {
                            let v167 = C::constructor_project(ctx, v166, v158.1);
                            // Rule at examples/database_optimizer/isle/rules.isle line 415.
                            returns.extend(Some(v167));
                            if returns.len() >= MAX_ISLE_RETURNS { return; }
                        }
                    }
                }
            }
        }
    }
    // Rule at examples/database_optimizer/isle/rules.isle line 261.
    returns.extend(Some(arg0));
    if returns.len() >= MAX_ISLE_RETURNS { return; }
}
